version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: metaversal_postgres_db
    environment:
      POSTGRES_USER: metaversal_db_user    
      POSTGRES_PASSWORD: metaversal_db_pw  
      POSTGRES_DB: metaversal_test_application
    ports:
      - "5432:5432"                
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
